//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notification.Api.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notification.Api.Messages.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is required and can not be null or empty..
        /// </summary>
        internal static string ContactCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ContactCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required and can not be null or empty..
        /// </summary>
        internal static string MessageInvalid {
            get {
                return ResourceManager.GetString("MessageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageType is required and must be between 0 and 3..
        /// </summary>
        internal static string MessageTypeInvalid {
            get {
                return ResourceManager.GetString("MessageTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page value must be greater than 1..
        /// </summary>
        internal static string PageCannotBeLessThanOne {
            get {
                return ResourceManager.GetString("PageCannotBeLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerPage value must be between 50 and 100..
        /// </summary>
        internal static string PerPageMustToBeWithinRange {
            get {
                return ResourceManager.GetString("PerPageMustToBeWithinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId is required and can not be null or empty..
        /// </summary>
        internal static string ProductIdInvalid {
            get {
                return ResourceManager.GetString("ProductIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName is required and can not be null or empty..
        /// </summary>
        internal static string ProductNameInvalid {
            get {
                return ResourceManager.GetString("ProductNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectId is required and can not be null or empty..
        /// </summary>
        internal static string ProjectIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProjectIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientNumber is required and can not be null or empty..
        /// </summary>
        internal static string RecipientNumberInvalid {
            get {
                return ResourceManager.GetString("RecipientNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitIt is required and can not be null or empty..
        /// </summary>
        internal static string UnitIdInvalid {
            get {
                return ResourceManager.GetString("UnitIdInvalid", resourceCulture);
            }
        }
    }
}
